using System;

namespace BSOL.Core.Entities
{
    public class Employment
    {
        public long ID { get; set; }
        public long DesignationID { get; set; }
        public long CategoryID { get; set; }
        public long LevelID { get; set; }
        public DateTime DOJ { get; set; }
        public int ProbationPeriod { get; set; }
        public long? ProbationRatingID { get; set; }
        public string EmploymentType { get; set; }
        public TimeSpan StartTime { get; set; }
        public TimeSpan S2StartTime { get; set; }
        public TimeSpan PHStartTime { get; set; }
        public TimeSpan PHS2StartTime { get; set; }
        public TimeSpan GHStartTime { get; set; }
        public TimeSpan GHS2StartTime { get; set; }
        public TimeSpan WOStartTime { get; set; }
        public TimeSpan WOS2StartTime { get; set; }
        public TimeSpan EndTime { get; set; }
        public TimeSpan S1EndTime { get; set; }
        public TimeSpan PHEndTime { get; set; }
        public TimeSpan PHS1EndTime { get; set; }
        public TimeSpan GHEndTime { get; set; }
        public TimeSpan GHS1EndTime { get; set; }
        public TimeSpan WOEndTime { get; set; }
        public TimeSpan WOS1EndTime { get; set; }
        public TimeSpan Break { get; set; }
        public TimeSpan HDBreak { get; set; }
        public TimeSpan PHBreak { get; set; }
        public TimeSpan PHHDBreak { get; set; }
        public TimeSpan GHBreak { get; set; }
        public TimeSpan GHHDBreak { get; set; }
        public TimeSpan WOBreak { get; set; }
        public TimeSpan WOHDBreak { get; set; }
        public int AttendanceLeniency { get; set; }
        public TimeSpan MinWorkHours { get; set; }
        public TimeSpan HDMinWorkHours { get; set; }
        public TimeSpan PHMinWorkHours { get; set; }
        public TimeSpan PHHDMinWorkHours { get; set; }
        public TimeSpan GHMinWorkHours { get; set; }
        public TimeSpan GHHDMinWorkHours { get; set; }
        public TimeSpan WOMinWorkHours { get; set; }
        public TimeSpan WOHDMinWorkHours { get; set; }
        public string WeekOff1 { get; set; }
        public string WeekOff1Policy { get; set; }
        public string WeekOff2 { get; set; }
        public string WeekOff2Policy { get; set; }
        public int RequiredPunches { get; set; }
        public int HDRequiredPunches { get; set; }
        public int PHRequiredPunches { get; set; }
        public int PHHDRequiredPunches { get; set; }
        public int GHRequiredPunches { get; set; }
        public int GHHDRequiredPunches { get; set; }
        public int WORequiredPunches { get; set; }
        public int WOHDRequiredPunches { get; set; }
        public string WorkingType { get; set; }
        public string PublicHoliday { get; set; }
        public string GovernmentHoliday { get; set; }
        public bool OverTime { get; set; }
        public string OTBasedOn { get; set; }
        public int? ContractPeriod { get; set; }
        public int NoticePeriod { get; set; }
        public bool Pension { get; set; }
        public bool LTS { get; set; }
        public bool ServiceCharge { get; set; }
        public bool CompensationLeave { get; set; }
        public bool HolidayAllowance { get; set; }
        public bool PayrollApplicable { get; set; }
        public long? SuperiorID { get; set; }
        public long? MiraProfessionID { get; set; }
        public long SalaryPolicyID { get; set; }
        public decimal TotalSalary1 { get; set; }
        public decimal TotalSalary2 { get; set; }
        public string PayThrough1 { get; set; }
        public int? BankID1 { get; set; }
        public string AccountName1 { get; set; }
        public string AccountNo1 { get; set; }
        public long? CompanyAccountID1 { get; set; }
        public string PayThrough2 { get; set; }
        public int? BankID2 { get; set; }
        public string AccountName2 { get; set; }
        public string AccountNo2 { get; set; }
        public long? CompanyAccountID2 { get; set; }
        public decimal? ProbationIncrement { get; set; }
        public long? ProbationAddedTo { get; set; }
        public long? GroupID { get; set; }
        public int? NoOfTicket { get; set; }
        public string WorkSite { get; set; }
        public DateTime? AppliedFrom { get; set; }
        public bool Active { get; set; }
        public string EntryBy { get; set; }
        public DateTime EntryDate { get; set; }
    }
}
